# Render configuration for Glass

services:
  # Next.js Web Dashboard
  - type: web
    name: glass-web
    runtime: node
    plan: free # or starter ($7/mo) for better performance
    buildCommand: cd pickleglass_web && npm install && npm run build
    startCommand: cd pickleglass_web && npm start
    envVars:
      # Firebase
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      
      # Firebase Admin (server-side)
      - key: FIREBASE_ADMIN_PROJECT_ID
        sync: false
      - key: FIREBASE_ADMIN_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_ADMIN_PRIVATE_KEY
        sync: false
      
      # Stripe
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      
      # PostHog
      - key: NEXT_PUBLIC_POSTHOG_KEY
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_HOST
        value: https://app.posthog.com
      
      # URLs
      - key: NEXT_PUBLIC_URL
        generateValue: false
      - key: UPDATE_SERVER_URL
        generateValue: false
      - key: pickleglass_API_URL
        generateValue: false
      
      # Node
      - key: NODE_VERSION
        value: 18
      
      # Environment
      - key: NODE_ENV
        value: production

# Optional: Background Worker (if needed)
# - type: worker
#   name: glass-worker
#   runtime: node
#   plan: free
#   buildCommand: npm install
#   startCommand: npm run worker

